# Line numbers matter here! (see toggle-monitor-config.sh)
# Presets are marked by '# [NAME]' headers.
# Only one preset should have active monitor= lines; others should be #monitor=.

# [HOME]
monitor=eDP-1,preferred,0x0,1
#monitor=HDMI-A-1,1920x1080,1920x0,1

# [EFAC]
#monitor=HDMI-A-1,preferred,0x-1200,1 # Top
